### ISSUE TITLE
it took so much time to open share bottom sheet

### ISSUE THREAD

**Issue by singlakaran** [aarajput/wc_flutter_share#1]

**Comment by aarajput** [comment]
Are you talking about android or ios?

**Comment by singlakaran** [comment]
android

**Comment by aarajput** [comment]
Which device are you using?

**Comment by singlakaran** [comment]
one plus 7

**Comment by aarajput** [comment]
Can you share your code here which you are using to share stuff?

**Comment by singlakaran** [comment]
GestureDetector(
          child: IconShare(),
          onTap: () {
            print('click share profile');
            WcFlutterShare.share(
                sharePopupTitle: 'Share',
                text: profileUrl,
                mimeType: 'text/plain');
          },
        ),

**Comment by aarajput** [comment]
Have you tried this on emulator? Because it could be your device issue.
Try it on emulator or try restarting your device.
This plugin just calls Share intent on android. After that, this intent handles by android O.S.

**Comment by singlakaran** [comment]
i tried other device also 
samsung A20 infinity
one plus 6t

**Comment by aarajput** [comment]
Try to replace your code with this one. And let know the value you see in console for _time diff_

GestureDetector(
              child: IconShare(),
              onTap: () async {
                print('click share profile');
                final startTime = DateTime.now();
                print('start time: $startTime');
                await WcFlutterShare.share(
                    sharePopupTitle: 'Share',
                    text: profileUrl,
                    mimeType: 'text/plain');
                final endTime = DateTime.now();
                print('end time: $startTime');
                print(
                    'time diff: ${endTime.millisecond - startTime.millisecond}');
              },
            ),

**Comment by singlakaran** [comment]
i used your code but it also takes time 
time diff: 3

**Comment by aarajput** [comment]
It's taking only 3 milliseconds.

I believe there is an issue with your code.
Try cloning this repository and run example on your device and let me know if you are facing same issue.
I am trying to figure it out if this issue is related to this plugin or your code.

**Comment by singlakaran** [comment]
i cloned but it takes too much time to open

**Comment by aarajput** [comment]
Please run `flutter doctor` share share it with me.

**Comment by Katekko** [comment]
Here is completely normal..
