### ISSUE TITLE
Share dialog doesn't show on iPadOS ^3.1

### ISSUE THREAD

**Issue by ejain** [aarajput/wc_flutter_share#10]
Likely the same issue as https://github.com/esysberlin/esys-flutter-share/issues/46; see also https://github.com/flutter/flutter/issues/19607.

**Comment by aarajput** [comment]
I will check this issue.

**Comment by neckaros** [comment]
> I will check this issue.

Any updates?

**Comment by ejain** [comment]
Looks like https://github.com/flutter/plugins/pull/970 is close to being merged, which would make this plugin obsolete.

**Comment by aarajput** [comment]
I don't think so. As main purpose of this plugin is to share text + subject + file at the same time.
I will look into this issue today.

**Comment by neckaros** [comment]
I did a fix for esys share if it can help:
https://github.com/esysberlin/esys-flutter-share/pull/54

**Comment by aarajput** [comment]
Thanks a lot @neckaros . This definitely will help me to fix this issue.

**Comment by aarajput** [comment]
I have release version 0.2.0 with the fix of iPad share. I am closing this issue.

**Comment by MaskyS** [comment]
> As main purpose of this plugin is to share text + subject + file at the same time.

#970 on the flutter plugin implements that. Nevertheless, thanks for having provided this meanwhile!
