### ISSUE TITLE
Latest Instagram Version Sharing Image to Instagram Feed Doesn't Work

### ISSUE THREAD

**Issue by erdoganabaci** [aarajput/wc_flutter_share#13]
**Describe the bug**
In the **latest version** of instagram (133.0.0.32.120 ) it only creates problems when feeding pictures
Instagram story and video feature works well but **just sharing image to instagram feed doesn't work.**
However every feature works well **in the previous version of Instagram (132.0.0.26.134 )**

**Expected behavior**
Image file is expected to shared to feed via instagram latest version

**Screenshots**
![Screenshot_1584893077](https://user-images.githubusercontent.com/43154455/77254199-b2cae600-6c70-11ea-8853-6817614ddcca.png)

![Screenshot_1584892335](https://user-images.githubusercontent.com/43154455/77253885-962dae80-6c6e-11ea-81d4-6a6b1dc1ea6e.png)

**Smartphone (please complete the following information):**
 - Device: Android Api 28
 - Instagram Version [133.0.0.32.120]

**Additional context**
Please help how to solve instagram to feed image in the instagram latest version(133.0.0.32.120).

**Comment by aarajput** [comment]
Does your instagram app has read storage permission?

**Comment by erdoganabaci** [comment]
Yes I have already added.But problem is only new version.I tried your example also didn't work.Problem about **new version Instagram (133.0.0.32.120 )**.Previous versions works good but **latest instagram version didnt work share feed image to instagram**

This is permissions

![github bug permisson](https://user-images.githubusercontent.com/43154455/77254550-beb7a780-6c72-11ea-8ead-22d4de6bd99d.png)

**Comment by aarajput** [comment]
Have your tried sharing from other app to instagram?

**Comment by erdoganabaci** [comment]
Yes I tried other application.Again couldnt work.if it looks at you from your own example file it doesn't work too.

**Comment by aarajput** [comment]
If even other apps are not able to share anything on instagram, then this could be a bug of instagram.

**Comment by erdoganabaci** [comment]
Sorry I wrote wrongly other apps works good.Only your widget sharing instagram to feed doesnt work.Could you try your own example to share image feed instagram? It doesnt work

**Comment by aarajput** [comment]
Sorry about that. I will take a look at it tomorrow.

**Comment by erdoganabaci** [comment]
Ok I am waiting good news. Please try instagram new version to share feed to Instagram.Story works good but Instagram feed couldnt work.Thank you for your response.

**Comment by aarajput** [comment]
I am no longer facing this issue.
