### ISSUE TITLE
Wrong Share modal position on tablet (iPad OS) 

### ISSUE THREAD

**Issue by thaoula** [aarajput/wc_flutter_share#14]
Hi @aarajput,

I have been trying to use your plugin on iPadOS and I found the them modal dialog seems to be placed wrong.

![image](https://user-images.githubusercontent.com/349133/78423273-71363400-768f-11ea-9293-94ff9500fc7f.png)

A similar issue for another flutter sharing plugin
https://github.com/esysberlin/esys-flutter-share/issues/40

Do you know how we can fix this issue?

Regards,
Tarek

**Comment by aarajput** [comment]
Hi,
Sorry for this issue. I will add a feature to add offset for your anchor point for ipad share dialog.

**Comment by grappetite-ali** [comment]
Hi @thaoula ! I have updated this package to 0.2.1. In it, i have added property *iPadConfig* to change anchor point of share dialog in iPad.

I am closing this issues.
