### ISSUE TITLE
Release mode not work

### ISSUE THREAD

**Issue by phcaraujo** [aarajput/wc_flutter_share#15]
I am using the plugin to share photo and text, however, in the release version of the application sharing does not work.

When I'm using the debug version the sharing works perfectly.

Can someone help me?

```
void _shareImageAndText() async {
    try {
      var imageUrl = 'https://www.dropestore.com/img/07717000.jpg';
      var imageId = await ImageDownloader.downloadImage(imageUrl);
      var path = await ImageDownloader.findPath(imageId);
      var mimeType = await ImageDownloader.findMimeType(imageId);
      final ByteData bytes = await rootBundle.load(path);
      await WcFlutterShare.share(
          sharePopupTitle: 'share',
          subject: 'Title',
          text:
              'Body message',
          fileName: 'share.jpg',
          mimeType: mimeType,
          bytesOfFile: bytes.buffer.asUint8List());
    } catch (e) {
      print('error: $e');
    }
  }
```

**Comment by Yashank18** [comment]
Same I am using the same code and it's working fine when I am on debug mode. Can you please tell is this about any android permissions?
@aarajput

**Comment by aarajput** [comment]
Have you tried adding internet permission in main manifest file?

**Comment by Yashank18** [comment]
Yes, I have added internet permission, read external permission and write external permission as well.

**Comment by aarajput** [comment]
Is it throwing some exception?

**Comment by Yashank18** [comment]
@aarajput  No, when I use this in debug or on my emulator it works fine and pretty accurate but when I use this is my released apk/ built apk. It doesn't work at all

**Comment by aarajput** [comment]
Have you tried example code?

**Comment by Yashank18** [comment]
Yes, it is not working with release mode

**Comment by aarajput** [comment]
Strange. I will look into this.

**Comment by Yashank18** [comment]
@aarajput any updates, I need to use this in my app that is completed. Can you please tell me any solution?

**Comment by Yashank18** [comment]
@aarajput What I think is we need some other permissions as well her because in debug mode application have all the permissions but while release apk, there is a need for some more dependencies.

**Comment by aarajput** [comment]
I am sorry, I didn't get time to look into this issue. Can you fork this repo and try to fix it and send me p.r?

**Comment by Yashank18** [comment]
@aarajput  I will try

**Comment by aarajput** [comment]
There is an issue with your implementation. I have tested this on example.
