### ISSUE TITLE
A problem occurred configuring project ':wc_flutter_share'

### ISSUE THREAD

**Issue by walide67** [aarajput/wc_flutter_share#16]
after run the project i get the following issue :

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':wc_flutter_share'.
> > Could not resolve all artifacts for configuration ':wc_flutter_share:classpath'.
>    > Could not download kotlin-gradle-plugin.jar (org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61)
>       > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.61/kotlin-gradle-plugin-1.3.61.jar'.
>          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.61/kotlin-gradle-plugin-1.3.61.jar'.
>             > jcenter.bintray.com: Temporary failure in name resolution
>    > Could not download kotlin-compiler-embeddable.jar (org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.61)
>       > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.61/kotlin-compiler-embeddable-1.3.61.jar'.
>          > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.3.61/kotlin-compiler-embeddable-1.3.61.jar'.
>             > jcenter.bintray.com
> > Failed to notify project evaluation listener.
>    > Could not get unknown property 'android' for project ':wc_flutter_share' of type org.gradle.api.Project.
>    > Could not find method implementation() for arguments [project ':path_provider'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 15m 41s
> Gradle task assembleDebug failed with exit code 1

flutter version : 1.12.13

**Comment by aarajput** [comment]
Try to open android project and sync gradle

**Comment by aarajput** [comment]
@walide67 ! Are you still facing this issue?
