### ISSUE TITLE
Nothing it happend

### ISSUE THREAD

**Issue by mbdax034** [aarajput/wc_flutter_share#17]
Hello thank for all,

Share text or image not working and no exception is thrown
wc_flutter_share: ^0.2.1
test in Android device
Flutter (Channel master, 1.18.0-10.0.pre, on Linux, locale fr_FR.UTF-8)

**Comment by aarajput** [comment]
Have you tried example project? Is it working?

**Comment by mbdax034** [comment]
Yes i done and it works, 
it is because i'have classpath 'com.android.tools.build:gradle:3.5.3'  ?

**Comment by aarajput** [comment]
Please close this issue if your problem has been solved.

**Comment by mbdax034** [comment]
The problem is not soved ?

**Comment by aarajput** [comment]
But you just told me that issue is with your Gradle version.

**Comment by mbdax034** [comment]
it's a question
 'it is because i'have classpath 'com.android.tools.build:gradle:3.5.3' **?**"

**Comment by aarajput** [comment]
I don't think so. I could be an issue with you implementation. Can you paste your code here?

**Comment by steve28100** [comment]
Same issue here. This is my code:

Nothing special:

```
WcFlutterShare.share( sharePopupTitle: widget.eventModel.title,
subject: widget.eventModel.title,
text: 'Let's join us!',
mimeType: 'text/plain')
```

My project already migrated to androidx and also this is working fine using version 0.2.0. So I think my implementation already correct. Please check. Thank you!

**Comment by aarajput** [comment]
Can you please share your app gradle file, kotlin version and response of flutter doctor here?

**Comment by shaxxx** [comment]
I can confirm the same problem.
Using version 0.2.1 on Android to share screenshot and nothing happens.
![wc_flutter_share](https://user-images.githubusercontent.com/1778875/83720653-c4017d00-a639-11ea-83d8-507e43a84f45.jpg)
Version 0.2.0 works as expected, share dialog opens up nicely.

> flutter doctor -v
> [√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.778], locale hr-HR)
>     • Flutter version 1.17.2 at C:\src\flutter
>     • Framework revision 5f21edf8b6 (6 days ago), 2020-05-28 12:44:12 -0700
>     • Engine revision b851c71829
>     • Dart version 2.8.3
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at C:\Android\sdk
>     • Platform android-29, build-tools 29.0.2
>     • ANDROID_HOME = C:\Android\sdk
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.8052
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.45.1)
>     • VS Code at C:\Users\isako\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.11.0
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 10 (API 29) (emulator)
> 
> • No issues found!

You can find all additional files in my GitHub repository
https://github.com/shaxxx/Signalmeter2

**Comment by aarajput** [comment]
Thanks. I will clone your repo and run your project.

**Comment by aarajput** [comment]
@shaxxx ! I tried running your project. But i can't find share button in your app.
Can you please guide me ?

**Comment by shaxxx** [comment]
Sure, you can find it [HERE](https://github.com/shaxxx/Signalmeter2/blob/fb74b94aa34d60f7597eac5a8265fdb6e883a3a2/lib/src/ui/screenshot/screenshot_view.dart#L65)
It's on the screenshot page, available in the app bar.

But unfortunatelly, there is no 'out of the box' way to try this without actual satellite receiver. 
You'll have to modify the code to call this method directly.

**Comment by aarajput** [comment]
@shaxxx ! I thanks for giving access to your repo. I have fixed this issue. 
I have released version 0.2.2 please try this version and close this ticket if its fixed.

**Comment by shaxxx** [comment]
I can confirm that 0.2.2 works on Android and iPhone.
You'll need to close it yourself, I'm not the one who opened this ticket.
Thanks.

**Comment by aarajput** [comment]
Perfect. I am closing this ticket now.
