### ISSUE TITLE
ios: trying to save shared image closes app without error

### ISSUE THREAD

**Issue by esskar** [aarajput/wc_flutter_share#19]
I am trying to save the image that i am sharing on iOS. The app crashes without notification/error

```
void _onSharePressed() async {
    try {
      final boundary =
          _qrCodeKey.currentContext.findRenderObject() as RenderRepaintBoundary;
      final image = await boundary.toImage(pixelRatio: 3);
      final byteData = await image.toByteData(format: ImageByteFormat.png);
      await WcFlutterShare.share(
          sharePopupTitle: 'share',
          subject: 'This is subject',
          text: 'This is text',
          fileName: 'test.png',
          mimeType: 'image/png',
          bytesOfFile: byteData.buffer.asUint8List());
    } catch (e) {
      print('error: $e');
    }
  }
```

Choosing to send the image by email, instagram, whatsapp works without problems. Saving to files works as well. Only save image crashes.

iPhone 8, ios 13.4.1

**Comment by aarajput** [comment]
Thanks for creating pointingout this issue, i just checked. It is crashing. I am looking into this.

**Comment by akshatjagga** [comment]
Have you set the required fields in info.plist?

**Comment by aarajput** [comment]
@akshatjagga !! What fields ?

**Comment by lehaidangdev** [comment]
@aarajput @esskar you should declare 2 fields in Info.plist to grant permission to access ios's library.
It's only happend when build app for ios >= 10 or 11.
<key>NSPhotoLibraryAddUsageDescription</key>
<string>Message</string>	
<key>NSPhotoLibraryUsageDescription</key>	
<string>Messae</string>

**Comment by aarajput** [comment]
Thanks for your help @lehaidangdev . I will add this in documentation.

**Comment by esskar** [comment]
works. thanks. (Y)
