### ISSUE TITLE
unable to share both image and text in ios device

### ISSUE THREAD

**Issue by rajagopalankothai** [aarajput/wc_flutter_share#23]
unable to share both image and text in ios device and in andriod it is working perfect..

**Comment by aarajput** [comment]
With which application are you trying to share?

**Comment by babaosoftware** [comment]
Same problem here:
Android works fine. Test messenger and email.
iPhone: messenger only shows the image, no text; email shows text as both subject and body

**Comment by rajagopalankothai** [comment]
I tried with IPhone 6.

**Comment by aarajput** [comment]
With which application are you trying to share image and text?

**Comment by babaosoftware** [comment]
I ended up using https://pub.dev/packages/esys_flutter_share which seems to be pretty much the same plugin. There is a pull request for esys_flutter_share to solve this problem on iOS, https://github.com/esysberlin/esys-flutter-share/pull/67, but it's not yet merged, so I cloned it and used it. It fixes the problem. You might have to fix the swift calls if you get a compile error.

**Comment by aarajput** [comment]
Thanks @babaosoftware ! I will look into it an fix this issue in next update.

**Comment by ezamagni** [comment]
Experiencing the same problem.
Might be afflicting iOS >= 13

**Comment by aarajput** [comment]
I'll at this issue

**Comment by Skogsfrae** [comment]
Are there any news on this? I'm stuck with this problem :(

**Comment by aarajput** [comment]
@babaosoftware ! I have release version 0.4.0. In it i have added your suggested code to fix image sharing issue. let me know if you still face issue. 
I am closing this ticket.
