### ISSUE TITLE
Consider pubspec update for path_provider

### ISSUE THREAD

**Issue by azack** [aarajput/wc_flutter_share#28]
Consider upgrading the dependencies for this project, possibly in conjunction with a semver bump.

The dependency of `path_provider` has a new major version, currently `2.0.1`: https://pub.dev/packages/path_provider

Other major projects such as `firebase_auth` now require the new version of `path_provider`, so users using both may encounter pub get errors such as:
```
Because path_provider >=1.6.4 <2.0.0-nullsafety depends on path_provider_platform_interface ^1.0.1 which depends on plugin_platform_interface ^1.0.1, path_provider >=1.6.4 <2.0.0-nullsafety requires plugin_platform_interface ^1.0.1.
And because firebase_auth >=1.0.0 depends on firebase_core_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, path_provider >=1.6.4 <2.0.0-nullsafety is incompatible with firebase_auth >=1.0.0.
```

**Comment by MeAtPros** [comment]
@stonega @Katekko Any update in that case?

**Comment by gehad-ahmed-mohamed** [comment]
Any updates for this issue?

**Comment by stonega** [comment]
@gehad-ahmed-mohamed  @MeAtPros Use dependency override. Add below to your pubspec.
```
 dependency_overrides:
  plugin_platform_interface: ^1.0.1
```

**Comment by MeAtPros** [comment]
the proposed solution is not a solution;) We ask realistically when to introduce this update

**Comment by gehad-ahmed-mohamed** [comment]
you can add this to pubspec file until any one updates the plugin .. this fixed my case

`dependency_overrides:
  path_provider: ^2.0.1`

**Comment by aarajput** [comment]
I will update this plugin this week.

**Comment by MeAtPros** [comment]
@aarajput Thanks, We look forward for a quick solution.

**Comment by MeAtPros** [comment]
@aarajput Any update in that case?

**Comment by aarajput** [comment]
I will fix this on weekend

**Comment by MeAtPros** [comment]
@aarajput We are looking forward to this update

**Comment by MeAtPros** [comment]
@aarajput I see the weekend end and there is still no update you promised

**Comment by aarajput** [comment]
I have publish 0.3.1 with your fix
