### ISSUE TITLE
iOS Video Share

### ISSUE THREAD

**Issue by DeepashreeB** [aarajput/wc_flutter_share#29]
Trying to share stored video with local path with text, but its not working. Video only not loading

final ByteData bytes = await rootBundle.load('$playListLocalPath');  
                await WcFlutterShare.share(  
                    sharePopupTitle: 'share',  
                    subject: 'This is subject',  
                    text: 'This is text',  
                    fileName: 'Name.mp4',  
                    mimeType: 'video/mp4',  
                    bytesOfFile: bytes.buffer.asUint8List());

**Comment by aarajput** [comment]
What is the size of video ?
