### ISSUE TITLE
File provider issue

### ISSUE THREAD

**Issue by Faiyyaz** [aarajput/wc_flutter_share#7]
E/MethodChannel#wc_flutter_share(22217): Failed to handle method call
E/MethodChannel#wc_flutter_share(22217): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority ooo.introadmin.app.fileprovider.github.com/com/wisecrab/wc-flutter-share
E/MethodChannel#wc_flutter_share(22217): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
E/MethodChannel#wc_flutter_share(22217): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/MethodChannel#wc_flutter_share(22217): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#wc_flutter_share(22217): 	at com.wisecrab.wc_flutter_share.WcFlutterSharePlugin.onShare(WcFlutterSharePlugin.kt:55)
E/MethodChannel#wc_flutter_share(22217): 	at com.wisecrab.wc_flutter_share.WcFlutterSharePlugin.onMethodCall(WcFlutterSharePlugin.kt:27)
E/MethodChannel#wc_flutter_share(22217): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#wc_flutter_share(22217): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#wc_flutter_share(22217): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#wc_flutter_share(22217): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#wc_flutter_share(22217): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#wc_flutter_share(22217): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#wc_flutter_share(22217): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#wc_flutter_share(22217): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#wc_flutter_share(22217): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#wc_flutter_share(22217): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter (22217): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Couldn't find meta-data for provider with authority ooo.introadmin.app.fileprovider.github.com/com/wisecrab/wc-flutter-share, null)
E/flutter (22217): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (22217): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (22217): <asynchronous suspension>
E/flutter (22217): #2      WcFlutterShare.share (package:wc_flutter_share/wc_flutter_share.dart:44:14)
E/flutter (22217): <asynchronous suspension>
E/flutter (22217): #3      CustomDrawer.getBody.<anonymous closure> (package:ooo.introadmin.app/ui/customview/custom_drawer.dart:49:38)
E/flutter (22217): <asynchronous suspension>
E/flutter (22217): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (22217): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (22217): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (22217): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (22217): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (22217): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (22217): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (22217): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (22217): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (22217): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (22217): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (22217): #15     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (22217): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (22217): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (22217): #18     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (22217): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (22217):

**Comment by aarajput** [comment]
Please share logs of `flutter doctor`
and share your manifest file and package.yaml.

**Comment by Faiyyaz** [comment]
Working fine. I had added a provider tag in manifest file after removing it is working fine.

Thank you
